all: tree-create tree-search tree-create2 tree-search2 tree-search3

tree-create: tree-create.c btree.c btree.h
	gcc -ggdb3 -o tree-create tree-create.c btree.c

tree-create2: tree-create2.c btree.c btree.h
	gcc -ggdb3 -o tree-create2 tree-create2.c btree.c

tree-search: tree-search.c btree.c btree.h
	gcc -ggdb3 -o tree-search tree-search.c btree.c

tree-search2: tree-search2.c btree.c btree.h
	gcc -ggdb3 -o tree-search2 tree-search2.c btree.c

tree-search3: tree-search3.c btree.c btree.h
	gcc -ggdb3 -o tree-search3 tree-search3.c btree.c
